---
resources:
- name: python-master
  type: git
  source: &repo-source
    uri: https://github.com/tripleaceinnovations/heloworld
    branch: master

task-config: &task-config
  platform: linux
  image_resouce:
    type: docker-image
    source:
      repository: python
  run:
    path: echo
    args:
      - 'This is where we will ship the product'

jobs:
- name: hello-job
  plan:
    - get: python-master
    - task: helotask
      config:
        platform: linux
        image_resouce:
          type: registry-image
          source: { repository: busybox }
        run:
          path: echo
          args: ["Hello, world!"]
- name: ship-it
  plan:
    - get: python-master
      passed: [hello-job]
    - task: heloshiptask
      config:
        << : *task-config
