---
resources:
- name: python-master
  type: git
  source:
    uri: https://github.com/tripleaceinnovations/heloworld
    branch: master

jobs:
- name: hello-job
  plan:
    - get: python-master
    - task: helotask
      file: python-master/heloworld/myhelotask.yml
- name: ship-it
  plan:
    - get: python-master
      passed: [hello-job]
    - task: heloshiptask
      file: python-master/heloworld/myshipithelotask.yml
