---
resource_types:
- name: python
  type: docker-image
  source:
    repository: tripleaceinnovations/python
    tag: latest

resources:
- name: test-python
  type: python
  source:
    url: http://www.qwantz.com/rssfeed.php

resources:
  - name: helloworld-master
    type: git
    source:
      uri: https://github.com/tripleaceinnovations/helloworld
      branch: master

jobs:
- name: helloworld-job
    public: true
    plan:
      - get: helloworld-master
      - task: helloworld-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: python }
          run:
            path: echo
            args: ["Hello, world!"]